version: '3.5'

services:
  database:
    image: postgres:latest
    container_name: kameticket_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - database:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - database
    restart: unless-stopped
  admindatabase:
    image: dpage/pgadmin4
    container_name: kameticket_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_ADMIN_PASSWORD}
    ports:
      - '8081:80'
    depends_on:
      - database
    networks:
      - database
  # cache:
  #   image: redis:latest
  #   container_name: kameticket_redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - cache:/data
  # messagebroker:
  #   image: rabbitmq:3.8.9-management
  #   container_name: kameticket_rabbitmq
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   networks:
  #     - database
  #   volumes:
  #     - messagebroker:/var/lib/rabbitmq
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  #   restart: unless-stopped

networks:
  database:
    driver: bridge

volumes:
  database:
  # cache:
  # messagebroker:
